groups:
  - name: api_alerts
    interval: 15s
    rules:
      - alert: gold_api_down
        expr: sum(service_status{service="gold-api"} or (absent(service_status{service="gold-api"}) == 1) * 0) == 0
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: "Gold API is down"
          description: "The Gold API has been down."

      - alert: currency_api_down
        expr: up{instance="currency-api:3002", job="currency-api"} == 0
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: "Currency API is down"
          description: "The Currency API has been down."

      - alert: container_gold_not_running
        expr: |
          (time() - container_last_seen{name="gold-api"} < bool 15) == 0
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: Container Gold not running
          description: "container gold is down"

      - alert: container_currency_not_running
        expr: |
          (time() - container_last_seen{name="currency-api"} < bool 15) == 0
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: Container Currency not running
          description: "container currency is down"

      - alert: cpu_overloaded
        expr: |
          (((count(count(node_cpu_seconds_total{instance="52.64.68.139:9100",job="node_exporter"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance="52.64.68.139:9100",job="node_exporter"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance="52.64.68.139:9100",job="node_exporter"}) by (cpu)) > 80
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: CPU is nearly overloaded
          description: "CPU is nearly overloaded"
